name: Publish package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish Base24Serial
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: Base24Serial\Base24Serial.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        TAG_FORMAT: v*
